services:
  script-hub:
    image: xxooyy/script-hub:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:9100"
    environment:
      - BASE_URL=${BASE_URL}
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true