networks:
  1panel-network:
    external: true

services:
  kibana:
    image: kibana:8.15.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:5601
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${KIBANA_ROOT_PATH}/data:/usr/share/kibana/data
    environment:
      - SERVER_NAME="kibana"
      - SERVER_HOST="0.0.0.0"
      - SERVER_PORT=5601
      - I18N_LOCALE="zh-CN"
      - SERVER_SHUTDOWNTIMEOUT="5s"
      - MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=true
