services:
  cloudflared:
    image: cloudflare/cloudflared:2024.8.3
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    command: tunnel --no-autoupdate run --token ${CFD_TOKEN}
    labels:  
      createdBy: "Apps"

networks:
    1panel-network:
        external: true
