version: "3.8"

networks:
  1panel-network:
    external: true

services:
  ghost:
    image: ghost:5.88.3
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:2368
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${BARK_ROOT_PATH}/data:/var/lib/ghost/content
    environment:
      - NODE_ENV=production
      - server__host=127.0.0.1
      - server__port=2368
      - database__client=mysql
