name: hoarder
version: latest
tags:
- 书签管理
- AI工具
- 笔记
description:
  zh: "Hoarder 是一个自托管的全能书签管理工具，支持保存链接、笔记和图片。具有基于 AI 的自动标签功能和全文搜索能力，让您的收藏更加智能和易于管理。"
  en: "Hoarder is a self-hostable bookmark-everything app that supports links, notes, and images. It features AI-based automatic tagging and full-text search capabilities for smarter content management."
home: https://github.com/hoarder-app/hoarder
author: hoarder-app
website: https://github.com/hoarder-app/hoarder
repository: ghcr.io/hoarder-app/hoarder
containers:
  - name: hoarder
    image: ghcr.io/hoarder-app/hoarder:latest
    ports:
      - container_port: 3000
        host_port: 3000
    volumes:
      - mount_path: /data
        host_path: /data
      - mount_path: /config
        host_path: /config
    environments:
      - key: TZ
        value: Asia/Shanghai
    restart: unless-stopped

args:
  - key: storage_path
    type: string
    value: /data/storage
    description:
      zh: "数据存储路径"
      en: "Storage Path"
    required: true