version: '3'
services:
  lucky:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: host
    volumes:
      - ${DATA_PATH}/luckyconf:/goodluck
    image: gdy666/lucky:2.6.2
    labels:  
      createdBy: "Apps"
