version: "3.8"

networks:
  1panel-network:
    external: true

services:
  nacos:
    image: nacos/nacos-server:v2.4.1
    container_name: ${CONTAINER_NAME}
    restart: always
    labels:
      createdBy: "Apps"
    network_mode: ${NETWORK_MODE}
    ports:
      - ${PANEL_APP_PORT_HTTP}:8848
      - ${PANEL_APP_PORT_GRPC_CLIENT}:9848
      - ${PANEL_APP_PORT_GRPC_SERVER}:9849
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${NACOS_ROOT_PATH}/logs:/home/nacos/logs
      - ${NACOS_ROOT_PATH}/data:/home/nacos/data
    environment:
      - MODE=standalone
      - NACOS_SERVER_PORT=8848
      - NACOS_AUTH_ENABLE=true
      - SPRING_DATASOURCE_PLATFORM=mysql
