version: "3.8"

networks:
  1panel-network:
    external: true

services:
  minio:
    image: minio/minio:RELEASE.2024-06-11T03-13-30Z
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
      - ${PANEL_APP_PORT_API}:${MINIO_API_PORT}
    command: server --console-address :${PANEL_APP_PORT_HTTP} --address :${MINIO_API_PORT} --json
    environment:
      - MINIO_VOLUMES=/data
      - MINIO_API_ROOT_ACCESS=on
      - MINIO_BROWSER_REDIRECT=true
    env_file:
      - .env
    extra_hosts:
      - ${MINIO_SERVER_HOST:-localhost}:127.0.0.1
    volumes:
      - ${MINIO_ROOT_PATH}/certs:/root/.minio/certs
      - ${MINIO_ROOT_PATH}/data:/data
    logging:
      options:
        max-size: "5M"
        max-file: "10"
      driver: json-file
