version: "3.3"
services:
  mw-server:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    privileged: true
    ports:
        - "${Web_Panel_Port}:7200"
        - "${HTTP_PORT}:80"
        - "${HTTPS_PORT}:443"
        - "${phpMyAdmin_PORT}:888"
    volumes:
        - mw-server:/www
    image: "ddsderek/mw:latest"
    labels:  
      createdBy: "Apps"
volumes:
  mw-server:
networks:  
  1panel-network:  
    external: true

