version: "3.8"

networks:
  1panel-network:
    external: true

services:
  cookie-cloud:
    image: easychen/cookiecloud:latest
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8088
    volumes:
      - ${COOKIECLOUD_ROOT_PATH}/data:/data/api/data
    env_file:
      - .env
