services:
  libretv:
    image: "bestzwei/libretv:latest"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}"
    labels:  
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
