services:
  anqicms:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8001"
    image: anqicms/anqicms:v3.4.1
    labels:  
      createdBy: "Apps"
networks:  
  1panel-network:  
    external: true
