networks:
  1panel-network:
    external: true

services:
  nexusphp:
    image: qyg2297248353/nexusphp:v1.8.14
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
    env_file:
      - /etc/1panel/envs/global.env
      - /etc/1panel/envs/nexusphp/nexusphp.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${NEXUSPHP_ROOT_PATH}/config/.env.example:/var/www/html/.env.example
      - ${NEXUSPHP_ROOT_PATH}/data:/var/www/html
      - ${NEXUSPHP_TORRENTS_ROOT_PATH}/torrents:/var/www/html/torrents
      - ${NEXUSPHP_BITBUCKET_ROOT_PATH}/bitbucket:/var/www/html/bitbucket
      - ${NEXUSPHP_ATTACHMENTS_ROOT_PATH}/attachments:/var/www/html/attachments
    environment:
      - TIMEZONE=Asia/Shanghai
      - APP_DEBUG=false
      - APP_ENV=production
      - LOG_LEVEL=info
      - DB_CONNECTION=mysql
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - MAIL_FROM_NAME=${APP_NAME}
      - SFTP_ROOT=/tmp
      - GEOIP2_DATABASE=/var/www/html/geoip2/geoip2.mmdb
