version: "3.8"

networks:
  1panel-network:
    external: true

services:
  linkding:
    image: sissbruecker/linkding:1.31.0-plus-alpine
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:9090
    volumes:
      - ${LINKDING_ROOT_PATH}/data:/etc/linkding/data
    env_file:
      - .env
    environment:
      - LD_SERVER_PORT=9090
      - LD_DB_ENGINE=postgres
      - HTTP_PROXY=${ALL_PROXY}
      - HTTPS_PROXY=${ALL_PROXY}
