services:
    resilio-sync:
        image: lscr.io/linuxserver/resilio-sync:latest
        container_name: ${CONTAINER_NAME}
        restart: always
        ports:
            - ${PANEL_APP_PORT_HTTP}:8888
            - ${PANEL_APP_PORT_SYNC}:55555
        volumes:
            - ./config:/config
            - ./downloads:/downloads
            - ./data:/sync
        networks:
            - 1panel-network
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Shanghai
        labels:
            createdBy: Apps
networks:
    1panel-network:
        external: true
