networks:
  1panel-network:
    external: true

services:
  sonarr:
    image: linuxserver/sonarr:4.0.9
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8989
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${PROWLARR_ROOT_PATH}/config:/config
      - ${PROWLARR_ROOT_PATH}/tv:/tv
      - ${PROWLARR_ROOT_PATH}/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Asia/Shanghai
