version: '3'
services:
  music-tag-web:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8001"
    volumes:
      - "${DATA_PATH}:/app/media:z"
    command: /start
    image: registry.cn-hangzhou.aliyuncs.com/charles0519/music_tag_web:1.2.5
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
