version: '3'
services:
  zerotier-one:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: host
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - ./data:/var/lib/zerotier-one
    image: bltavares/zerotier:1.14.0
    labels:  
      createdBy: "Apps"
