version: "3"
services:
  wireguard:
    container_name: ${CONTAINER_NAME}-wireguard
    restart: always
    networks:
      - 1panel-network
    cap_add:
      - NET_ADMIN
    volumes:
      - ${DATA_PATH}/config:/config
    ports:
      - "${PANEL_APP_PORT_HTTP}:5000"
      - "${WIREGUARD_PORT}:51820/udp"
    image: linuxserver/wireguard:latest
    labels:  
      createdBy: "Apps"

  wireguard-ui:
    container_name: ${CONTAINER_NAME}
    restart: always
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=${WEBUI_USER}
      - WGUI_PASSWORD=${WEBUI_PWD}
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
    volumes:
      - ${DATA_PATH}/db:/app/db
      - ${DATA_PATH}/config:/etc/wireguard
    image: ngoduykhanh/wireguard-ui:0.5.2
    logging:
      driver: json-file
      options:
        max-size: 50m
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true

