version: "3.8"

networks:
  1panel-network:
    external: true

services:
  nacos:
    image: nacos/nacos-server:v2.3.1
    container_name: ${CONTAINER_NAME}
    restart: always
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8848
      - ${NACOS_COMMUNICATION_PORT}:9848
    volumes:
      - ${NACOS_ROOT_PATH}/logs:/home/nacos/logs
      - ${NACOS_ROOT_PATH}/data:/home/nacos/data
    environment:
      - MODE=standalone
      - NACOS_SERVER_PORT=8848
      - NACOS_AUTH_ENABLE=true
      - SPRING_DATASOURCE_PLATFORM=mysql
    env_file:
      - .env
