version: '3'
services:
  grafana:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    volumes:
      - ./data:/var/lib/grafana
    user: '0'
    image: grafana/grafana:10.4.1
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
