version: "3.8"

networks:
  1panel-network:
    external: true

services:
  rsshub:
    image: diygod/rsshub:chromium-bundled-2024-08-06
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:1200
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    environment:
      - NODE_ENV=production
      - PORT=1200
      - LISTEN_INADDR_ANY=1
      - REQUEST_RETRY=2
      - REQUEST_TIMEOUT=3000
      - ALLOW_ORIGIN=*
      - CACHE_CONTENT_EXPIRE=360
      - CACHE_EXPIRE=300
      - MEMORY_MAX=256
