networks:
  1panel-network:
    external: true

services:
  qbittorrent:
    container_name: ${CONTAINER_NAME}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUIPORT=${PANEL_APP_PORT_HTTP}
      - ENABLE_DOWNLOADS_PERM_FIX=true
    image: superng6/qbittorrentee:latest
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_PEER}:6881
      - ${PANEL_APP_PORT_PEER}:6881/udp
      - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
    restart: always
    volumes:
      - ./data/config:/config
      - ./data/downloads:/downloads
