services:
  xiaomusic:
    image: hanxi/xiaomusic
    container_name: xiaomusic
    restart: unless-stopped
    ports:
      - ${APP_PORT_58090}:8090
    environment:
      XIAOMUSIC_PUBLIC_PORT: ${APP_PORT_58090}
      TZ: ${TZ}
    volumes:
      - ${APP_DATA}/music:/app/music
      - ${APP_DATA}/conf:/app/conf
      - /xiaomusic_conf:/app/conf
