networks:
  1panel-network:
    external: true

services:
  komga:
    image: gotson/komga:1.18.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    user: 1000:1000
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:25600
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${KOMGA_ROOT_PATH}/config:/config
      - ${KOMGA_ROOT_PATH}/data:/data
    environment:
      - TZ=Asia/Shanghai
