services:
  loliafrp:
    image: ghcr.io/lolia-frp/loliacli-frpc:0.71.0
    container_name: ${CONTAINER_NAME}
    network_mode: host
    command: -t ${TUNNER_ID}:${NODE_TOKEN}
    volumes:
      - ./autotls-cache:/.autotls-cache
    labels:
      createdBy: Apps
