version: "3.8"

networks:
  1panel-network:
    external: true

services:
  dockge:
    image: louislam/dockge:1.4.2
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:5001
    volumes:
      - ${DOCKGE_ROOT_PATH}/data:/app/data
      - ${DOCKGE_ROOT_PATH}/stacks:/opt/dockge/stacks
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKGE_STACKS_DIR=/opt/dockge/stacks
