version: "3.8"

networks:
  1panel-network:
    external: true

services:
  transmission:
    image: linuxserver/transmission:4.0.3
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    network_mode: ${NETWORK_MODE}
    ports:
      - ${PANEL_APP_PORT_HTTP}:9091
      - ${PANEL_APP_PORT_TORRENTING}
      - ${PANEL_APP_PORT_TORRENTING}/udp
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${TRANSMISSION_ROOT_PATH}/config:/config
      - ${TRANSMISSION_ROOT_PATH}/downloads:/downloads
      - ${TRANSMISSION_ROOT_PATH}/watch:/watch
      - ${CUSTOM_MOUNT_DIRECTORY_1:-./default_mount_1}:${CUSTOM_MOUNT_DIRECTORY_1:-/default_mount_1}
      - ${CUSTOM_MOUNT_DIRECTORY_2:-./default_mount_2}:${CUSTOM_MOUNT_DIRECTORY_2:-/default_mount_2}
      - ${CUSTOM_MOUNT_DIRECTORY_3:-./default_mount_3}:${CUSTOM_MOUNT_DIRECTORY_3:-/default_mount_3}
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - PEERPORT= ${PANEL_APP_PORT_TORRENTING}
