networks:
  1panel-network:
    external: true

services:
  nodebb:
    image: ghcr.io/nodebb/nodebb:3.12.2
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:4567
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${NODEBB_ROOT_PATH}/node_modules:/usr/src/app/node_modules
      - ${NODEBB_ROOT_PATH}/build:/usr/src/app/build
      - ${NODEBB_ROOT_PATH}/uploads:/usr/src/app/public/uploads
      - ${NODEBB_ROOT_PATH}/config:/opt/config
    environment:
      - TZ=Asia/Shanghai
      - bind_address=0.0.0.0
      - port=4567
      - url=http://127.0.0.1:4567
      - database=${NODEBB_DB}
      - ${NODEBB_DB}__host=${NODEBB_DB_HOST}
      - ${NODEBB_DB}__port=${NODEBB_DB_PORT}
      - ${NODEBB_DB}__database=${NODEBB_DB_NAME}
      - ${NODEBB_DB}__username=${NODEBB_DB_USER}
      - ${NODEBB_DB}__password=${NODEBB_DB_PASSWORD}
