services:
  peerbanhelper:
    image: registry.cn-hangzhou.aliyuncs.com/ghostchu/peerbanhelper:v6.2.7
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:9898"
    volumes:
      - "${DATA_PATH}/peerbanhelper:/app/data"
    labels:  
      createdBy: "Apps"
networks:  
  1panel-network:  
    external: true
