services:
  lanraragi:
    user: root
    container_name: lanraragi
    restart: always
    networks:
      - 1panel-network
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "3000:3000"
    volumes:
      - content:/home/koyomi/lanraragi/content
      - thumbnails:/home/koyomi/lanraragi/content/thumb
      - database:/home/koyomi/lanraragi/database
      - plugin:/home/koyomi/lanraragi/lib/LANraragi/Plugin
      - Sideloaded:/home/koyomi/lanraragi/lib/LANraragi/PluginSideloaded
    image: difegue/lanraragi
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true

volumes:
  content:
  thumbnails:
  database:
  plugin:
  Sideloaded:
