services:
  easytier:
    image: "easytier/easytier:latest"
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: host
    privileged: ${PRIVILEGED_MODE}
    hostname: ${HOSTNAME}
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - ${DATA_PATH}:/root
    command: ${COMMAND}
    labels:
      createdBy: "Apps"
