networks:
  1panel-network:
    external: true
services:
  sun-panel:
    container_name: ${CONTAINER_NAME}
    environment:
      - TZ=Asia/Shanghai
    image: hslr/sun-panel:latest
    labels:
      createdBy: Apps
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:3002
    restart: always
    volumes:
      - ./data/conf:/app/conf
      - ./data/database:/app/database
      - ./data/uploads:/app/uploads
