networks:
  1panel-network:
    external: true

services:
  dpanel:
    image: dpanel/dpanel:1.1.4
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8080
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${DPANEL_ROOT_PATH}/data:/dpanel
      - /var/run/docker.sock:/var/run/docker.sock
