networks:
  1panel-network:
    external: true

services:
  maccms10:
    image: qyg2297248353/maccms10:v20.10.14
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${MACCMS10_ROOT_PATH}/iycms:/app/iycms
