version: "3.8"

networks:
  1panel-network:
    external: true

services:
  speedtest:
    image: ghcr.io/librespeed/speedtest:5.3.3
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
    volumes:
      - ${SPEED_TEST_ROOT_PATH}/database:/database
    environment:
      - MODE=standalone
      - WEBPORT=80
    env_file:
      - .env
