version: "3.8"

networks:
  1panel-network:
    external: true

services:
  casdoor:
    image: casbin/casdoor:v1.645.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8000
    build:
      context: ./
      dockerfile: Dockerfile
      target: STANDARD
    entrypoint: /bin/sh -c './server --createDatabase=true'
    volumes:
      - ${CASDOOR_ROOT_PATH}/data/files:/home/user/casdoor/files
    environment:
      - driverName=${DB_TYPE}
      - dbName=${DB_NAME}
      - redisEndpoint=${REDIS_HOSTNAME}:${REDIS_PORT}
      - verificationCodeTimeout=10
      - appname="casdoor"
      - authState="casdoor"
