version: "3.8"

networks:
  1panel-network:
    external: true

services:
  deeplx:
    image: qyg2297248353/deeplx:v0.9.5.1
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP:-1188}
    environment:
      - PORT=${PANEL_APP_PORT_HTTP:-1188}
    env_file:
      - .env
