version: "3"
services:
  frpc:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: "host"
    volumes:
        #- "${CONFIG_FILE_PATH}:/etc/frp/frpc.ini" #截止5.1.3版本使用ini
        - "${CONFIG_FILE_PATH}:/etc/frp/frpc.toml"
    image: "snowdreamtech/frpc:0.53.2"
    labels:  
      createdBy: "Apps"
