networks:
  1panel-network:
    external: true

services:
  cloudreve:
    image: loudreve/cloudreve:4.0.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:5212
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${CLOUDREVE_ROOT_PATH}/data:/cloudreve/data
    environment:
      - TZ=Asia/Shanghai
