networks:
  1panel-network:
    external: true

services:
  synapse-init:
    image: matrixdotorg/synapse:v1.118.0
    container_name: synapse-init
    entrypoint: >
      /bin/sh -c "
      if [ ! -f /data/homeserver.yaml ]; then
        python3 -m synapse.app.homeserver --server-name ${SYNAPSE_SERVER_NAME} --config-path /data/homeserver.yaml --generate-config
      fi
      "
    environment:
      - SYNAPSE_SERVER_NAME=${DOMAIN_NAME}
      - SYNAPSE_REPORT_STATS=no
    volumes:
      - ${SYNAPSE_ROOT_PATH}/data:/data
    networks:
      - 1panel-network
    restart: no
  synapse:
    image: matrixdotorg/synapse:v1.118.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8008
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${SYNAPSE_ROOT_PATH}/data:/data
    depends_on:
      - synapse-init
