services:
    linkwarden:
        image: ghcr.io/linkwarden/linkwarden:latest
        container_name: ${CONTAINER_NAME}
        restart: always
        ports:
            - ${PANEL_APP_PORT_HTTP}:3000
        volumes:
            - ./data:/data/data
        networks:
            - 1panel-network
        environment:
            - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
        depends_on:
            - postgres
            - meilisearch
        env_file:
            - .env
        labels:
            createdBy: Apps
    meilisearch:
        image: getmeili/meilisearch:v1.12.8
        container_name: ${CONTAINER_NAME}-Meilisearch
        restart: always
        volumes:
            - ./meili_data:/meili_data
        env_file:
            - .env
        networks:
            - 1panel-network
        labels:
            createdBy: Apps
    postgres:
        image: postgres:16-alpine
        container_name: ${CONTAINER_NAME}-Postgres
        restart: always
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        env_file:
            - .env
        networks:
            - 1panel-network
        labels:
            createdBy: Apps
networks:
    1panel-network:
        external: true
