networks:
  1panel-network:
    external: true

services:
  onedev:
    image: 1dev/server:11.2.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:6610
      - ${PANEL_APP_PORT_SSH}:6611
    volumes:
      - ${ONEDEV_ROOT_PATH}/data:/opt/onedev
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - /etc/1panel/envs/global.env
      - /etc/1panel/envs/onedev/onedev.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    environment:
      - initial_user=${INITIAL_USER}
      - initial_password=${INITIAL_PASSWORD}
      - initial_email=${INITIAL_EMAIL}
      - initial_server_url=${INITIAL_SERVER_URL}
      - initial_ssh_root_url=${INITIAL_SSH_ROOT_URL}
