services:
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
      - "${PANEL_APP_PORT_HTTPS}:3001"
    volumes:
      - /path/to/wireshark/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined #optional
    network_mode: host