discovery:
  type: single-node

network:
  host: 0.0.0.0

http:
  host: 0.0.0.0
  port: 9200
  cors:
    enabled: true
    allow-origin: "*"

path:
  repo:
    - /usr/share/elasticsearch/backup

xpack:
  security:
    enabled: true
    autoconfiguration:
      enabled: true
    enrollment:
      enabled: true
