version: "3.8"

networks:
  1panel-network:
    external: true

services:
  elasticsearch:
    image: elasticsearch:8.14.3
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    tty: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - ${PANEL_APP_PORT_HTTPS}:9200
      - ${PANEL_APP_PORT_API}:9300
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${BARK_ROOT_PATH}/certs:/usr/share/elasticsearch/config/certs
      - ${BARK_ROOT_PATH}/data:/usr/share/elasticsearch/data
      - ${BARK_ROOT_PATH}/logs:/usr/share/elasticsearch/logs
      - ${BARK_ROOT_PATH}/plugins:/usr/share/elasticsearch/plugins
    environment:
      - LICENSE=basic
      - ES_SETTING_BOOTSTRAP_MEMORY__LOCK=true
      - TAKE_FILE_OWNERSHIP=true
