networks:
  1panel-network:
    external: true
services:
  paopao-ce:
    image: bitbus/paopao-ce:all-in-one-0.6-alpha
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network
    restart: always
    ports:
      - ${PANEL_APP_PORT_HTTP}:8008
      - ${PANEL_APP_PORT_MEILI}:7700
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${PAOPAO_CE_ROOT_PATH}/config/config.yaml:/app/config.yaml
      - ${PAOPAO_CE_ROOT_PATH}/custom:/app/custom
      - ${PAOPAO_CE_ROOT_PATH}/meili_data:/app/meili_data
