version: '3'
services:
  safeline-mgt:
    container_name: ${CONTAINER_NAME}-mgt
    restart: always
    networks:
      1panel-network:
        ipv4_address: ${SUBNET_PREFIX}.234
    image: chaitin/safeline-mgt:4.0.1
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${SAFELINE_DIR}/resources/mgt:/app/data
    ports:
    - ${PANEL_APP_PORT_HTTP:-9443}:1443
    environment:
    - MGT_PG=postgres://safeline-ce:${POSTGRES_PASSWORD}@safeline-pg/safeline-ce?sslmode=disable
    #- MGT_LICENSE_SERVER=https://safeline-ce-4463.rivers.chaitin.cn/
    dns: 
      - 119.29.29.29
      - 223.5.5.5
      - 180.76.76.76
      - 1.2.4.8
      - 114.114.114.114
      - 8.8.8.8
    depends_on:
      - safeline-pg
      - safeline-fvm
    labels:
      createdBy: Apps

  safeline-detector:
    container_name: ${CONTAINER_NAME}-detector
    restart: always
    networks:
      1panel-network:
        ipv4_address: ${SUBNET_PREFIX}.235
    image: chaitin/safeline-detector:4.0.1
    volumes:
    - ${SAFELINE_DIR}/resources/detector:/resources/detector
    - ${SAFELINE_DIR}/logs/detector:/logs/detector
    - /etc/localtime:/etc/localtime:ro
    environment:
    - LOG_DIR=/logs/detector
    labels:
      createdBy: Apps

  safeline-mario:
    container_name: ${CONTAINER_NAME}-mario
    restart: always
    networks:
      1panel-network:
        ipv4_address: ${SUBNET_PREFIX}.236
    image: chaitin/safeline-mario:4.0.1
    volumes:
    - ${SAFELINE_DIR}/resources/mario:/resources/mario
    - ${SAFELINE_DIR}/logs/mario:/logs/mario
    - /etc/localtime:/etc/localtime:ro
    environment:
    - LOG_DIR=/logs/mario
    - GOGC=100
    - DATABASE_URL=postgres://safeline-ce:${POSTGRES_PASSWORD}@safeline-pg/safeline-ce
    labels:
      createdBy: Apps

  safeline-tengine:
    container_name: ${CONTAINER_NAME}-tengine
    restart: always
    image: chaitin/safeline-tengine:4.0.1
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/resolv.conf:/etc/resolv.conf
    - ${SAFELINE_DIR}/resources/nginx:/etc/nginx
    - ${SAFELINE_DIR}/resources/detector:/resources/detector
    - ${SAFELINE_DIR}/logs/nginx:/var/log/nginx
    - ${SAFELINE_DIR}/resources/cache:/usr/local/nginx/cache
    environment:
    - TCD_MGT_API=https://${SUBNET_PREFIX}.234:1443/api/open/publish/server
    - SNSERVER_ADDR=${SUBNET_PREFIX}.235:8000
    ulimits:
      nofile: 131072
    network_mode: host
    labels:
      createdBy: Apps

  safeline-luigi:
    container_name: ${CONTAINER_NAME}-luigi
    restart: always
    networks:
      1panel-network:
        ipv4_address: ${SUBNET_PREFIX}.237
    image: chaitin/safeline-luigi:4.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SAFELINE_DIR}/resources/luigi:/app/data
    labels:
      createdBy: Apps

  safeline-fvm:
    container_name: ${CONTAINER_NAME}-fvm
    restart: always
    networks:
      1panel-network:
        ipv4_address: ${SUBNET_PREFIX}.238
    image: chaitin/safeline-fvm:4.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      createdBy: Apps

  safeline-pg:
    container_name: ${CONTAINER_NAME}-pg
    restart: always
    networks:
      1panel-network:
        ipv4_address: ${SUBNET_PREFIX}.232
    image: postgres:15.5-alpine
    volumes:
    - ${SAFELINE_DIR}/resources/postgres/data:/var/lib/postgresql/data
    - /etc/localtime:/etc/localtime:ro
    environment:
    - POSTGRES_USER=safeline-ce
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: [postgres, -c, max_connections=200]
    labels:
      createdBy: Apps

networks:
  1panel-network:
    external: true