networks:
  1panel-network:
    external: true

services:
  smtp_proxy_server:
    image: ghcr.io/dreamhunter2333/cloudflare_temp_email/smtp_proxy_server:v0.9.1
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_SMTP:-8025}:${PANEL_APP_PORT_SMTP:-8025}
      - ${PANEL_APP_PORT_IMAP:-11143}:${PANEL_APP_PORT_IMAP:-11143}
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    environment:
      - TZ=Asia/Shanghai
      - proxy_url=${PROXY_URL}
      - port=${PANEL_APP_PORT_SMTP:-8025}
      - imap_port=${PANEL_APP_PORT_IMAP:-11143}
