version: "3.8"

networks:
  1panel-network:
    external: true

name: immich-machine-learning

services:
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.108.0
    container_name: immich-machine-learning-${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    devices:
      - /dev/dri:/dev/dri
    ports:
      - ${PANEL_APP_PORT_HTTP}:3003
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${IMMICH_ROOT_PATH}/data/cache:/cache
