version: "3.8"
services:
  nodebb:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:4567"
    volumes:
      - ./data:/usr/src/app/public/uploads
    image: nodebb/docker:1.19
    labels:  
      createdBy: "Apps"
    
networks:  
  1panel-network:  
    external: true
