services:
  transmission:
    container_name: ${CONTAINER_NAME}
    image: lscr.io/linuxserver/transmission:latest
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:9091"
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./watch:/watch
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true 