networks:
  1panel-network:
    external: true

services:
  radarr:
    image: linuxserver/radarr:5.9.1
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:7878
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${RADARR_ROOT_PATH}/config:/config
      - ${RADARR_ROOT_PATH}/movies:/movies
      - ${RADARR_ROOT_PATH}/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Asia/Shanghai
