networks:
  1panel-network:
    external: true

services:
  dashdot:
    image: mauricenino/dashdot:nvidia-5.9.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    ports:
      - ${PANEL_APP_PORT_HTTP}:3001
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - /:/mnt/host:ro
    environment:
      - DASHDOT_WIDGET_LIST=os,cpu,storage,ram,network,gpu
