services:
  uuwaf:
    image: "uusec/nanqiang:v5.2.0"
    ulimits:
      nproc: 65535
      nofile:
        soft: 102400
        hard: 102400
    container_name:  ${CONTAINER_NAME}
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
      - ${PANEL_APP_PORT_HTTPS}:443
      - ${PANEL_APP_PORT_CONSOLE}:4443
    volumes:
      - wafshared:/uuwaf
    command: ["/run.sh"]
    environment:
      - TZ=${TIME_ZONE}
      - UUWAF_MYSQL_PASSWORD=${PANEL_DB_USER_PASSWORD}
    links:
      - wafdb
    depends_on:
       wafdb:
         condition: service_healthy
  wafdb:
    image: "percona/percona-server:5.7.44"
    container_name:  ${CONTAINER_NAME}-db
    networks:
      - 1panel-network
    volumes:
      - wafshared:/docker-entrypoint-initdb.d
      - wafdata:/var/lib/mysql
      - ./low-memory-my.cnf:/etc/mysql/my.cnf
    environment:
      - TZ=${TIME_ZONE}
      - INIT_ROCKSDB
      - MYSQL_MAX_CONNECTIONS=${MYSQL_MAX_CONNECTIONS}
      - MYSQL_ROOT_PASSWORD=${PANEL_DB_USER_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      start_period: 0s
      interval: 5s
      timeout: 3s
      retries: 3
volumes:
  wafshared:
    name: wafshared
  wafdata:
    name: wafdata
networks:
  1panel-network:
    external: true