services:
  blinko:
    image: "blinkospace/blinko:1.0.3"
    container_name: ${CONTAINER_NAME}
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      DATABASE_URL: postgresql://${PANEL_DB_USER}:${PANEL_DB_USER_PASSWORD}@${PANEL_DB_HOST}:${PANEL_DB_PORT}/${PANEL_DB_NAME}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - "./data:/app/.blinko"
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "${PANEL_APP_PORT_HTTP}:1111"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1111/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true