networks:
  1panel-network:
    external: true

services:
  jellyseerr:
    image: fallenbagel/jellyseerr:1.9.2
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:5055
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${JELLYSEERR_ROOT_PATH}/config:/app/config
    environment:
      - PORT=5055
      - LOG_LEVEL=debug
      - TZ=Asia/Shanghai
      - https_proxy=${http_proxy:-}
