networks:
  1panel-network:
    external: true

services:
  kimai2:
    image: kimai/kimai2:apache-2.23.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8001
    volumes:
      - ${KIMAI2_ROOT_PATH}/data:/opt/kimai/var/data
      - ${KIMAI2_ROOT_PATH}/plugins:/opt/kimai/var/plugins
    command:
      - ADMINMAIL=admin@kimai.local
      - ADMINPASS=changemeplease
      - DATABASE_URL=mysql://${DB_USER}:${DB_USER_PASSWORD}@${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}?charset=utf8mb4
