networks:
  1panel-network:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.0.0-beta.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:3001
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${UPTIME_KUMA_ROOT_PATH}/data:/app/data
      - ${UPTIME_KUMA_ROOT_PATH}/server:/app/server
      - ${UPTIME_KUMA_ROOT_PATH}/db:/app/db
