version: '3'
services:
  alist:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:5244"
    volumes:
      - "${DATA_PATH}:/opt/alist/data"
      - "${MOUNT_PATH}:/mnt/data"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    image: xhofe/alist:v3.30.0@sha256:084ba82603563ac6e178d1d2bb90e6b3417efeca90a59aa75f7d1c60db7a5b26
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true

