services:
    whatsupdocker:
        image: getwud/wud:latest
        container_name: ${CONTAINER_NAME}
        ports:
            - ${PANEL_APP_PORT_HTTP}:3000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            WUD_AUTH_BASIC_ADMIN_USER: ${WUD_AUTH_BASIC_ADMIN_USER}
            WUD_AUTH_BASIC_ADMIN_HASH: ${WUD_AUTH_BASIC_ADMIN_HASH}
        networks:
            - 1panel-network
        labels:
            createdBy: Apps
networks:
    1panel-network:
        external: true
