networks:
  1panel-network:
    external: true
services:
  pixman:
    image: pixman/pixman:v1.7.7
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:5000
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${PIXMAN_ROOT_PATH}/m3u:/app/app/data/m3u
    environment:
      - http_proxy=${NETWORK_PROXY:-}
      - https_proxy=${NETWORK_PROXY:-}
