name: Renovate

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - localApps
  workflow_dispatch:
    inputs:
      manual-trigger:
        description: 'Manually trigger Renovate'
        default: ''

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Run Renovate
        uses: renovatebot/github-action@v40.3.4
        with:
          useSlim: false
          token: ${{ secrets.GITHUBTOKEN }}
