name: Renovate

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - localApps
  workflow_dispatch:
    inputs:
      manual-trigger:
        description: 'Manually trigger Renovate'
        default: ''

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.9
        with:
          useSlim: false
          token: ${{ secrets.GITHUBTOKEN }}
