networks:
  1panel-network:
    external: true

services:
  beszel:
    image: henrygd/beszel:0.11.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8090
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${BESZEL_ROOT_PATH}/data:/beszel_data
    environment:
      - TZ=Asia/Shanghai
