services:
  openlist-ffmpeg:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:5244"
      - "${PANEL_APP_PORT_S3}:5426"
    volumes:
      - ./data/data:/opt/openlist/data
      - ./data/mnt:/mnt/data
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    image: ghcr.io/openlistteam/openlist-git:v4.0.2-ffmpeg
    labels:  
      createdBy: "Apps"
networks:  
  1panel-network:  
    external: true

